---
- name: Create new LVM volume group
  lvg: vg={{ vgname }} pvs={{ disk }} state=present
  when: create_lvm

- name: Create new LVM logical volume
  lvol: vg={{ vgname }} lv={{ lvname }} size={{ lvsize }}
  when: create_lvm

- name: Create new filesystem on new LVM logical volume
  filesystem: fstype={{ filesystem }} dev=/dev/{{ vgname }}/{{ lvname }}
  when: create_lvm

- name: Mounting new filesystem
  mount: name={{ mnt_point }} src=/dev/{{ vgname }}/{{ lvname }} fstype={{ filesystem }} state=mounted
  when: create_lvm

- name: Unmount filesystem
  mount: name={{ mnt_point }} src=/dev/{{ vgname }}/{{ lvname }} fstype={{ filesystem }} state=unmounted
  when: remove_lvm

- name: Remove new LVM volume group
  lvol: vg={{ vgname }} lv={{ lvname }} state=absent force=yes
  when: remove_lvm

- name: Remove new LVM volume group
  lvg: vg={{ vgname }} pvs={{ disk }} state=absent force=yes
  when: remove_lvm
